---
- name: Ensure that the sudo package is installed
  tags: sudo
  become: true
  package:
    name: sudo
    state: present

- name: Attempting to overlay sudoers configurations
  tags: sudo
  become: true
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'

- name: Attempting to overlay sudoers.d configurations, if applicable
  tags: sudo
  become: true
  template:
    src: sudoers_d.j2
    dest: "{{ '/etc/sudoers.d/' + item.file }}"
    owner: root
    group: root
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
  loop: "{{ sudoers_d }}"
  loop_control:
    label: "{{ item.file }}"
  when:
    - item.commands is defined
    - item.file is defined
    - item.ugid is defined
...
